Numpyはndarrayと呼ばれるデータ型を用いる
Pandasは表はDataFrame、表から取り出した1行または1列はSeriesと呼ばれるデータ型を用いる


In [1]:
import numpy as np #numpyにnpという別名を付けてimport
import pandas as pd #pandasにpdという別名を付けてimport

#ndarrayの作り方
lst = [0, 1, 2]
nd = np.array(lst)
print(lst)
print(type(lst)) #lstはlist型
print(nd)
print(type(nd)) #ndはndarray型

print(lst * 2) #全要素の2回繰り返し
print(nd * 2) #全要素の数値が2倍

[0, 1, 2]
<class 'list'>
[0 1 2]
<class 'numpy.ndarray'>


In [4]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
print(a + b) #adarrayはいずれも対応する要素同士の演算になる
print(a * b)

[3 5 7]
[ 0  4 10]


In [5]:
#下の方が計算が高速
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = []
for i in range(len(a)):
    c.append(a[i] * b[i])
c = np.array(c)
print(c)

[ 0  4 10]


In [6]:
a1 = np.array([0, 1, 2])
a2 = np.array([[0, 1, 2], [3, 4, 5]])
a3 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(a1)
print(a2)
print(a3)

[0 1 2]
[[0 1 2]
 [3 4 5]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [7]:
#属性shapeは各軸（次元）の要素数
print(a1.shape) #3要素の1次元配列
print(a2.shape) #3要素の1次元配列が2つ並んだ2次元配列
print(a3.shape) #2行3列の2次元配列が2つ並んだ3次元配列

(3,)
(2, 3)
(2, 2, 3)


In [8]:
#DataFrameは、2次元のndarrayに行(index)と列(columns)を付加したもの
#pd.DataFrame関数に2次元リストとcolumnsを設定するためのリストを与えるとDataFrameを簡単に作れる
df = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns = ['c0', 'c1', 'c2'], index = ['r0', 'r1'])
print(type(df))
print(df.shape)
display(df) #displayはDataFrameを表にして表示してくれる

<class 'pandas.core.frame.DataFrame'>
(2, 3)


c0  c1  c2
r0   0   1   2
r1   3   4   5

In [9]:
#DataFrameのindex属性とcolumns属性にリストを代入することで、行番号と列ラベルを後で指定できる
df3 = pd.DataFrame([[0, 1, 2], [3, 4, 5]])
display(df3)                 
df3.index = ['r0', 'r1']
df3.columns = ['c0', 'c1', 'c2']
display(df3)

0  1  2
0  0  1  2
1  3  4  5

c0  c1  c2
r0   0   1   2
r1   3   4   5

In [10]:
#to_numpyメソッドでindexとcolumnsを除いた2次元のndarrayだけを取り出す事が出来る
print(type(df3.to_numpy()))
print(df3.to_numpy())

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]


In [35]:
#print(df.info())
#print(df.head(n)) nは書かないと5の初期設定
#print(df.tail())
#print(df.tail(N)) 末尾を表示させる

In [17]:
#変数 = pd.read_csv('CSVファイル名', sep=',', skiprows=N, header=M)
# もしくは 
# csv_in ='csvファイル名'
# 変数 = pd.read_csv('csv_in', sep=',', skiprows=N, header=M)
# 区切り字がTab文字の場合はsep='\t'、空白文字の場合はsep='\s+'とする。
# sep=を省略した場合は区切り字はコンマとみなされる

# 先頭の読み飛ばすべきデータ以外の行がない場合はskiprows=0とする

# 列ラベルの行がない場合はheader=Noneとする

In [18]:
# 変数 = データフレーム[列名]でデータフレーム（表）の１列分のデータを取り出せる
# 変数 = データフレーム[列名リスト]でデータフレームの複数のデータを取り出せる
#例　df1 = df[['Region', 'Milk', 'Grocery']]

In [19]:
# 複数列の取り出しは　変数 = データフレーム.loc[先頭行の行番号:末尾行の行番号, 先頭列の列ラベル:末尾列の列ラベル]
# 例 df3 = df.loc[1:3, 'Milk':'Frozen']
# 行番号や列ラベルを省略すると先頭から末尾までになる

In [20]:
# 列番号を用いて複数列を取り出す場合はilocを使う
# 変数 = データフレーム.iloc[先頭行の行番号:末尾行の１つ先の行番号, 先頭列の列番号:末尾列の１つ先の列番号]

In [21]:
# 一定間隔での取り出し、逆順での取り出し
# 例 display(df.iloc[2:15:2, 14:3:-1])
# 行番号2から14まで、2行ごと
# 列番号14から4まで、逆順に1列ごと

In [25]:
# ndarrayに対して各軸の番号を指定することで要素の値を取り出せる
a1 = np.array([0, 1, 2])
print(a1)
print(a1[0])

[0 1 2]
0


In [24]:
a2 = np.array([[0, 1, 2], [3, 4, 5]])
print(a2)
print(a2[0, 1])

[[0 1 2]
 [3 4 5]]
1


In [27]:
a3 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(a3)
print(a3[1, 0, 2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
8


In [29]:
# 取り出す代わりに値を代入すると値を変更できる
a1[0] = 99
print(a1)
a2[0, 1] = 99
print(a2)
a3[1, 0, 2] = 99
print(a3)

[99  1  2]
[[ 0 99  2]
 [ 3  4  5]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7 99]
  [ 9 10 11]]]


In [31]:
# DataFrameに対してatを使って行番号と列ラベルを指定できる
# print(df6.at[2, 'Frozen'])

In [32]:
# atの代わりにiatを使うと番号で1つの要素を指定できる
# print(df6.iat[2, 1])

In [34]:
# DataFrameでも値の代入によって要素の1つを変更できる
# df6.at[2, 'Frozen'] = 99
# df6.iat[2, 1] = 88