Numpyはndarrayと呼ばれるデータ型を用いる
Pandasは表はDataFrame、表から取り出した1行または1列はSeriesと呼ばれるデータ型を用いる


In [2]:
import numpy as np #numpyにnpという別名を付けてimport
import pandas as pd #pandasにpdという別名を付けてimport

#ndarrayの作り方
lst = [0, 1, 2]
nd = np.array(lst)
print(lst)
print(type(lst)) #lstはlist型
print(nd)
print(type(nd)) #ndはndarray型

print(lst * 2) #全要素の2回繰り返し
print(nd * 2) #全要素の数値が2倍

[0, 1, 2]
<class 'list'>
[0 1 2]
<class 'numpy.ndarray'>
[0, 1, 2, 0, 1, 2]
[0 2 4]


In [3]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
print(a + b) #adarrayはいずれも対応する要素同士の演算になる
print(a * b)

[3 5 7]
[ 0  4 10]


In [4]:
#下の方が計算が高速
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = []
for i in range(len(a)):
    c.append(a[i] * b[i])
c = np.array(c)
print(c)

[ 0  4 10]


In [5]:
a1 = np.array([0, 1, 2])
a2 = np.array([[0, 1, 2], [3, 4, 5]])
a3 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(a1)
print(a2)
print(a3)

[0 1 2]
[[0 1 2]
 [3 4 5]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [6]:
#属性shapeは各軸（次元）の要素数
print(a1.shape) #3要素の1次元配列
print(a2.shape) #3要素の1次元配列が2つ並んだ2次元配列
print(a3.shape) #2行3列の2次元配列が2つ並んだ3次元配列

(3,)
(2, 3)
(2, 2, 3)


In [7]:
#DataFrameは、2次元のndarrayに行(index)と列(columns)を付加したもの
#pd.DataFrame関数に2次元リストとcolumnsを設定するためのリストを与えるとDataFrameを簡単に作れる
df = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns = ['c0', 'c1', 'c2'], index = ['r0', 'r1'])
print(type(df))
print(df.shape)
display(df) #displayはDataFrameを表にして表示してくれる

<class 'pandas.core.frame.DataFrame'>
(2, 3)


c0  c1  c2
r0   0   1   2
r1   3   4   5

In [8]:
#DataFrameのindex属性とcolumns属性にリストを代入することで、行番号と列ラベルを後で指定できる
df3 = pd.DataFrame([[0, 1, 2], [3, 4, 5]])
display(df3)                 
df3.index = ['r0', 'r1']
df3.columns = ['c0', 'c1', 'c2']
display(df3)

0  1  2
0  0  1  2
1  3  4  5

c0  c1  c2
r0   0   1   2
r1   3   4   5

In [9]:
#to_numpyメソッドでindexとcolumnsを除いた2次元のndarrayだけを取り出す事が出来る
print(type(df3.to_numpy()))
print(df3.to_numpy())

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]


In [10]:
#print(df.info())
#print(df.head(n)) nは書かないと5の初期設定
#print(df.tail())
#print(df.tail(N)) 末尾を表示させる

In [11]:
#変数 = pd.read_csv('CSVファイル名', sep=',', skiprows=N, header=M)
# もしくは 
# csv_in ='csvファイル名'
# 変数 = pd.read_csv('csv_in', sep=',', skiprows=N, header=M)
# 区切り字がTab文字の場合はsep='\t'、空白文字の場合はsep='\s+'とする。
# sep=を省略した場合は区切り字はコンマとみなされる

# 先頭の読み飛ばすべきデータ以外の行がない場合はskiprows=0とする

# 列ラベルの行がない場合はheader=Noneとする

In [12]:
# 変数 = データフレーム[列名]でデータフレーム（表）の１列分のデータを取り出せる
# 変数 = データフレーム[列名リスト]でデータフレームの複数のデータを取り出せる
#例　df1 = df[['Region', 'Milk', 'Grocery']]

In [13]:
# 複数列の取り出しは　変数 = データフレーム.loc[先頭行の行番号:末尾行の行番号, 先頭列の列ラベル:末尾列の列ラベル]
# 例 df3 = df.loc[1:3, 'Milk':'Frozen']
# 行番号や列ラベルを省略すると先頭から末尾までになる

In [14]:
# 列番号を用いて複数列を取り出す場合はilocを使う
# 変数 = データフレーム.iloc[先頭行の行番号:末尾行の１つ先の行番号, 先頭列の列番号:末尾列の１つ先の列番号]

In [15]:
# 一定間隔での取り出し、逆順での取り出し
# 例 display(df.iloc[2:15:2, 14:3:-1])
# 行番号2から14まで、2行ごと
# 列番号14から4まで、逆順に1列ごと

In [16]:
# ndarrayに対して各軸の番号を指定することで要素の値を取り出せる
a1 = np.array([0, 1, 2])
print(a1)
print(a1[0])

[0 1 2]
0


In [17]:
a2 = np.array([[0, 1, 2], [3, 4, 5]])
print(a2)
print(a2[0, 1])

[[0 1 2]
 [3 4 5]]
1


In [18]:
a3 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(a3)
print(a3[1, 0, 2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
8


In [19]:
# 取り出す代わりに値を代入すると値を変更できる
a1[0] = 99
print(a1)
a2[0, 1] = 99
print(a2)
a3[1, 0, 2] = 99
print(a3)

[99  1  2]
[[ 0 99  2]
 [ 3  4  5]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7 99]
  [ 9 10 11]]]


In [20]:
# DataFrameに対してatを使って行番号と列ラベルを指定できる
# print(df6.at[2, 'Frozen'])

In [21]:
# atの代わりにiatを使うと番号で1つの要素を指定できる
# print(df6.iat[2, 1])

In [22]:
# DataFrameでも値の代入によって要素の1つを変更できる
# df6.at[2, 'Frozen'] = 99
# df6.iat[2, 1] = 88

In [23]:
import matplotlib.pyplot as plt #グラフ描画のためのライブラリmatplotlibをimportする

In [24]:
#カテゴリー変数の値を頻度はseriesのvalue_counts()で取得
#print(df['Region'].value_counts())
#データ数がわかる

In [25]:
#print(df.sum(axis=0)) 各列の和
#print(df.sum(axis=1)) 各行の和

In [27]:
#pandasにはsumに加えて以下のような様々な統計用関数が用意されている
#総和:sum()
#最小:min()
#最大:max
#平均:mean()
#中央値:median()
#分散(不偏分散):var() 母分散はvar(ddof=0)
#標準偏差(不偏標準偏差):std() 母標準偏差はstd(ddof=0)
#データフレームに非数値行が含まれているときはnumeric_only=Trueオプションを追加する

In [28]:
#Numpyの統計用関数
#総和:sum()
#最小:amin()
#最大:amax()
#平均:mean()
#中央:median()
#分散:(母分散):var() 不偏分散はvar(データ, ddof=1)
#標準偏差(母標準偏差):std() 不偏標準偏差はstd(データ, ddof=1)

In [33]:
#display(df.describe())　数値変数の列
#count:データ個数
#mean:平均
#std:標準偏差
#min:最小
#25％,50％,75％:各四分位数
#max:最大

In [34]:
#displau(df.describe(exclude=[np.number]))　カテゴリー変数の列
#count:データ個数
#unique:値の種類
#top:最頻値
#freq:最頻値の度数

In [35]:
#channel列は値は数値だがカテゴリー変数なのでdf.describe(exclude=[np.number])の方に表示させる方が適当です
#そのために、astypeメソッドを使ってchannel列のデータ型をcategoryに変更する
#df['Channel']=df['Channel'].astype('category')
#print(df.info) channel列のデータ型がcategoryに変わっている 

In [36]:
#plt.boxplot(df_num, labels=df_num.columns) 箱ひげ図を置く
#plt.xticks(rotation=90) x軸目盛ラベルを90度回転
#plt.ylabel('Annual spending [m.u.]')　y軸ラベルを設定
#plt.show()　グラフ全体を描画

In [37]:
#グラフ装飾用の関数
#plt.title() タイトル
#plt.xlabel()　ｘ軸ラベル
#plt.ylabel()　ｙ軸ラベル
#plt.xticks()　ｘ軸目盛ラベル
#plt.yticks()　ｙ軸目盛ラベル
#plt.xlim()　ｘ軸の描画範囲
#plt.ylim()　ｙ軸の描画範囲
#plt.xscale()　ｘ軸の目盛の種類
#plt.yscale()　ｙ軸の目盛の種類
#plt.legend()　凡例
#plt.tick_paramas()　目盛や軸ラベルなどの書式設定

In [38]:
#plt.boxplot(df_num[['Fresh','Grocery']], labels=['Fr','Gr'])
#plt.ylabel('Annual spending [m.u.]')
#plt.xticks(fontsize=24)
#plt.show()

In [39]:
#plt.hist(df_num['Fresh'])　ヒストグラムを置く
#plt.xlanel('Annual spending [m.u.]')　ｘ軸ラベルを設定
#plt.ylabel('Frequency')　ｙ軸ラベルを設定
#plt.show()　グラフ全体を描画

In [40]:
#オプション引数の例
#幅:bins=N (デフォルトはN=10）
#density=True　デフォルトはFalse　Trueにすると確率密度分布になる

In [41]:
#ser1 = 2 * df['Fresh'] + df['Frozen'] - 20000
#このように列の数値をまとめて一気に計算できる

In [43]:
#df['new_col'] = ser1 のようにdfに新しい列を追加できる

In [44]:
#dfから指定した列を削除する
#df_drop_c = df.drop(columns='Detergents_Paper') Detergents_Papaer列を削除する
#dfから指定した行を削除する
#df_drop_r = df.drop(index[1,3]) 1,3行目を削除する

In [47]:
#スライスで連続する行、列をして削除することもできる
#df_drop_c2 = df.drop(df.loc[:, 'Fresh':'Frozen'],axis=1)
#dfのFresh列からFrozen列までを削除
#df_drop_r2 = df.drop(df.index[1:3])
#dfの行番号1から2まで削除

In [ ]:
#