Numpyはndarrayと呼ばれるデータ型を用いる
Pandasは表はDataFrame、表から取り出した1行または1列はSeriesと呼ばれるデータ型を用いる


In [3]:
import numpy as np #numpyにnpという別名を付けてimport
import pandas as pd #pandasにpdという別名を付けてimport

#ndarrayの作り方
lst = [0, 1, 2]
nd = np.array(lst)
print(lst)
print(type(lst)) #lstはlist型
print(nd)
print(type(nd)) #ndはndarray型

print(lst * 2) #全要素の2回繰り返し
print(nd * 2) #全要素の数値が2倍

a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
print(a + b) #adarrayはいずれも対応する要素同士の演算になる
print(a * b)

#下の方が計算が高速
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = []
for i in range(len(a)):
    c.append(a[i] * b[i])
c = np.array(c)
print(c)

a1 = np.array([0, 1, 2])
a2 = np.array([[0, 1, 2], [3, 4, 5]])
a3 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(a1)
print(a2)
print(a3)
#属性shapeは各軸（次元）の要素数
print(a1.shape) #3要素の1次元配列
print(a2.shape) #3要素の1次元配列が2つ並んだ2次元配列
print(a3.shape) #2行3列の2次元配列が2つ並んだ3次元配列

#DataFrameは、2次元のndarrayに行(index)と列(columns)を付加したもの
#pd.DataFrame関数に2次元リストとcolumnsを設定するためのリストを与えるとDataFrameを簡単に作れる
df = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns = ['c0', 'c1', 'c2'], index = ['r0', 'r1'])
print(type(df))
print(df.shape)
display(df) #displayはDataFrameを表にして表示してくれる

#DataFrameのindex属性とcolumns属性にリストを代入することで、行番号と列ラベルを後で指定できる
df3 = pd.DataFrame([[0, 1, 2], [3, 4, 5]])
display(df3)                 
df3.index = ['r0', 'r1']
df3.columns = ['c0', 'c1', 'c2']
display(df3)

#to_numpyメソッドでindexとcolumnsを除いた2次元のndarrayだけを取り出す事が出来る
print(type(df3.to_numpy()))
print(df3.to_numpy())

[0, 1, 2]
<class 'list'>
[0 1 2]
<class 'numpy.ndarray'>
[0, 1, 2, 0, 1, 2]
[0 2 4]
[3 5 7]
[ 0  4 10]
[ 0  4 10]
[0 1 2]
[[0 1 2]
 [3 4 5]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(3,)
(2, 3)
(2, 2, 3)
<class 'pandas.core.frame.DataFrame'>
(2, 3)


c0  c1  c2
r0   0   1   2
r1   3   4   5

0  1  2
0  0  1  2
1  3  4  5

c0  c1  c2
r0   0   1   2
r1   3   4   5

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]
