#### Import libraries

In [2]:
import numpy as np 
import pandas as pd

#### Read CSV file

In [3]:
csv_in = 'wholesale_customers.csv'
df = pd.read_csv(csv_in, sep=',', skiprows=13, header=0)
print(df.shape)
print(df.info)
display(df.head())

(440, 8)
<bound method DataFrame.info of      Channel Region  Fresh   Milk  Grocery  Frozen  Detergents_Paper  \
0          2  Other  12669   9656     7561     214              2674   
1          2  Other   7057   9810     9568    1762              3293   
2          2  Other   6353   8808     7684    2405              3516   
3          1  Other  13265   1196     4221    6404               507   
4          2  Other  22615   5410     7198    3915              1777   
..       ...    ...    ...    ...      ...     ...               ...   
435        1  Other  29703  12051    16027   13135               182   
436        1  Other  39228   1431      764    4510                93   
437        2  Other  14531  15488    30243     437             14841   
438        1  Other  10290   1981     2232    1038               168   
439        1  Other   2787   1698     2510      65               477   

     Delicatessen  
0            1338  
1            1776  
2            7844  
3            1

Channel Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  \
0        2  Other  12669  9656     7561     214              2674   
1        2  Other   7057  9810     9568    1762              3293   
2        2  Other   6353  8808     7684    2405              3516   
3        1  Other  13265  1196     4221    6404               507   
4        2  Other  22615  5410     7198    3915              1777   

   Delicatessen  
0          1338  
1          1776  
2          7844  
3          1788  
4          5185

In [4]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=440, step=1)
Index(['Channel', 'Region', 'Fresh', 'Milk', 'Grocery', 'Frozen',
       'Detergents_Paper', 'Delicatessen'],
      dtype='object')


In [5]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols=None,
    squeeze: 'bool | None' = None,
    prefix: 'str | lib.NoDefault' = <no_default>,
    mangle_dupe_cols: 'bool' = True,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace: 'bool' = False,
    skiprows=None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values=None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool' = False,
    skip_blank_lines: 'bool' = True,
    parse_dates=None,
    infer

In [6]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols=None, squeeze: 'bool | None' = None, prefix: 'str | lib.NoDefault' = <no_default>, mangle_dupe_cols: 'bool' = True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace: 'bool' = False, skiprows=None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values=None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool' = False, skip_blank_lines: 'bool' = True, parse_dates=None, infer_datetime_format: 'bool' = False, keep_date_col: 'bool' = F

#### Extract one column

In [7]:
ser_region = df['Region']
print(type(ser_region))
print(ser_region)

<class 'pandas.core.series.Series'>
0      Other
1      Other
2      Other
3      Other
4      Other
       ...  
435    Other
436    Other
437    Other
438    Other
439    Other
Name: Region, Length: 440, dtype: object


#### Extract multiple columns

In [8]:
df2 = df[['Region', 'Milk', 'Grocery']]
print(type(df2))
display(df2.head())

<class 'pandas.core.frame.DataFrame'>


Region  Milk  Grocery
0  Other  9656     7561
1  Other  9810     9568
2  Other  8808     7684
3  Other  1196     4221
4  Other  5410     7198

#### Extract multiple rows/columns with loc

In [9]:
df3 = df.loc[1:3, 'Milk':'Frozen']
print(type(df3))
display(df3)

<class 'pandas.core.frame.DataFrame'>


Milk  Grocery  Frozen
1  9810     9568    1762
2  8808     7684    2405
3  1196     4221    6404

In [12]:
df4 = df.loc[:, 'Milk':]
display(df4)

Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
0     9656     7561     214              2674          1338
1     9810     9568    1762              3293          1776
2     8808     7684    2405              3516          7844
3     1196     4221    6404               507          1788
4     5410     7198    3915              1777          5185
..     ...      ...     ...               ...           ...
435  12051    16027   13135               182          2204
436   1431      764    4510                93          2346
437  15488    30243     437             14841          1867
438   1981     2232    1038               168          2125
439   1698     2510      65               477            52

[440 rows x 5 columns]

In [11]:
df5 = df.loc[:, :'Frozen']
display(df5)

Channel Region  Fresh   Milk  Grocery  Frozen
0          2  Other  12669   9656     7561     214
1          2  Other   7057   9810     9568    1762
2          2  Other   6353   8808     7684    2405
3          1  Other  13265   1196     4221    6404
4          2  Other  22615   5410     7198    3915
..       ...    ...    ...    ...      ...     ...
435        1  Other  29703  12051    16027   13135
436        1  Other  39228   1431      764    4510
437        2  Other  14531  15488    30243     437
438        1  Other  10290   1981     2232    1038
439        1  Other   2787   1698     2510      65

[440 rows x 6 columns]

#### Extract multiple rows/columns with iloc

In [13]:
df6 = df.iloc[1:4, 3:6]
display(df6)

Milk  Grocery  Frozen
1  9810     9568    1762
2  8808     7684    2405
3  1196     4221    6404

In [14]:
df7 = df.iloc[:, 3:]
display(df7)

Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
0     9656     7561     214              2674          1338
1     9810     9568    1762              3293          1776
2     8808     7684    2405              3516          7844
3     1196     4221    6404               507          1788
4     5410     7198    3915              1777          5185
..     ...      ...     ...               ...           ...
435  12051    16027   13135               182          2204
436   1431      764    4510                93          2346
437  15488    30243     437             14841          1867
438   1981     2232    1038               168          2125
439   1698     2510      65               477            52

[440 rows x 5 columns]

In [15]:
df8 = df.iloc[:, : -2]
display(df8)

Channel Region  Fresh   Milk  Grocery  Frozen
0          2  Other  12669   9656     7561     214
1          2  Other   7057   9810     9568    1762
2          2  Other   6353   8808     7684    2405
3          1  Other  13265   1196     4221    6404
4          2  Other  22615   5410     7198    3915
..       ...    ...    ...    ...      ...     ...
435        1  Other  29703  12051    16027   13135
436        1  Other  39228   1431      764    4510
437        2  Other  14531  15488    30243     437
438        1  Other  10290   1981     2232    1038
439        1  Other   2787   1698     2510      65

[440 rows x 6 columns]

In [16]:
display(df.iloc[-440:-435:2, 5:2:-1])

Frozen  Grocery  Milk
0     214     7561  9656
2    2405     7684  8808
4    3915     7198  5410

#### Slice of ndarray

In [17]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
b1 = a[:2, 1: -1]
print(b1)

[[1 2]
 [5 6]]


#### Extract an element (ndarray)

In [19]:
a1 = np.array([0, 1, 2])
print(a1)
print(a1[0])

[0 1 2]
0


In [20]:
a2 = np.array([[0, 1, 2], [3, 4, 5]])
print(a2)
print(a2[0, 1])

[[0 1 2]
 [3 4 5]]
1


In [23]:
a3 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(a3)
print(a3[1, 0, 2])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
8


#### Change the value of an element (ndarray)

In [24]:
a1[0] = 99 
print(a1)

[99  1  2]


In [25]:
a2[0, 1] = 99
print(a2)

[[ 0 99  2]
 [ 3  4  5]]


In [26]:
a3[1, 0, 2] = 99
print(a3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7 99]
  [ 9 10 11]]]


#### Extract an element (DataFrame)

In [27]:
display(df6)
print(df6.at[2, 'Frozen'])

Milk  Grocery  Frozen
1  9810     9568    1762
2  8808     7684    2405
3  1196     4221    6404

2405


In [28]:
print(df6.iat[2,1])

4221


#### Change the value of an element (DataFrame)

In [29]:
df6.at[2, 'Frozen'] = 99
display(df6)

Milk  Grocery  Frozen
1  9810     9568    1762
2  8808     7684      99
3  1196     4221    6404

In [30]:
df6.iat[2, 1] = 88
display(df6)

Milk  Grocery  Frozen
1  9810     9568    1762
2  8808     7684      99
3  1196       88    6404

#### Check read_csv options

In [31]:
csv_in = 'sample-sjis-semicolon.csv'
df_check = pd.read_csv(csv_in, sep=';', skiprows=0, header=None, encoding='shift-jis')
print(df_check.shape)
display(df_check.head())
df_check.columns=['c0', 'c1', 'c2', 'c3']
display(df_check.head())

(3, 4)


0   1   2   3
0   0   1   2  値1
1  10  11  12  値2
2  20  21  22  値3

c0  c1  c2  c3
0   0   1   2  値1
1  10  11  12  値2
2  20  21  22  値3

In [32]:
csv_in = 'sample-sjis-spaces.csv'
df_check = pd.read_csv(csv_in, sep='\s+', skiprows=0, header=None, encoding='shift-jis')
df_check.columns=['c0', 'c1', 'c2', 'c3']
print(df_check.shape)
display(df_check.head())

(3, 4)


c0  c1  c2  c3
0   0   1   2  値1
1  10  11  12  値2
2  20  21  22  値3

In [33]:
csv_in = 'sample-euc-tab.csv'
df_check = pd.read_csv(csv_in, sep='\t', skiprows=0, header=None, encoding='euc-jp')
df_check.columns=['c0', 'c1', 'c2', 'c3']
print(df_check.shape)
display(df_check.head())

(3, 4)


c0  c1  c2  c3
0   0   1   2  値1
1  10  11  12  値2
2  20  21  22  値3