In [3]:
import numpy as np

a = np.array([1, 3, 5])
b = np.array([5, 7, 9])
print(a, b)

print(type(a))

print(a + b)

print(a * b)

print(a.shape)

[1 3 5] [5 7 9]
<class 'numpy.ndarray'>
[ 6 10 14]
[ 5 21 45]
(3,)
