#### Import libraries

In [18]:
import numpy as np
import pandas as pd

#### List and ndarray

In [2]:
lst = [0, 1, 2]
nd = np.array(lst)
print(lst)
print(type(lst))
print(nd)
print(type(nd))

[0, 1, 2]
<class 'list'>
[0 1 2]
<class 'numpy.ndarray'>


In [3]:
print(lst * 2)
print(nd * 2)

[0, 1, 2, 0, 1, 2]
[0 2 4]


#### List and ndarray 2

In [5]:
a = [0, 1, 2]
b = [3, 4, 5]
print(type(a))
print(a + b)
#print(a * b)

<class 'list'>
[0, 1, 2, 3, 4, 5]


In [6]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
print(type(a))
print(a + b)
print(a * b)

<class 'numpy.ndarray'>
[3 5 7]
[ 0  4 10]


In [10]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = a * b
print(c)

a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = []
for i in range(len(a)):
    c.append(a[i] * b[i])
c = np.array(c)
print(c)

[ 0  4 10]
[ 0  4 10]


#### Check dimensions

In [14]:
a1 = np.array([0, 1, 2])
a2 = np.array([[0, 1, 2], [3, 4, 5]])
a3 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(a1)
print(a2)
print(a3)
print(a1.shape)
print(a2.shape)
print(a3.shape)

[0 1 2]
[[0 1 2]
 [3 4 5]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(3,)
(2, 3)
(2, 2, 3)


#### List and DateFrame

In [19]:
df = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns = ['c0', 'c1', 'c2'])
print(type(df))
print(df.shape)
display(df)

<class 'pandas.core.frame.DataFrame'>
(2, 3)


c0  c1  c2
0   0   1   2
1   3   4   5

In [20]:
df2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns = ['c0', 'c1', 'c2'], index = ['r0', 'r1'])
display(df2)

c0  c1  c2
r0   0   1   2
r1   3   4   5

In [20]:
df2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns = ['c0', 'c1', 'c2'], index = ['r0', 'r1'])
display(df2)

c0  c1  c2
r0   0   1   2
r1   3   4   5

In [20]:
df2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns = ['c0', 'c1', 'c2'], index = ['r0', 'r1'])
display(df2)

c0  c1  c2
r0   0   1   2
r1   3   4   5

In [23]:
df3 = pd.DataFrame([[0, 1, 2], [3, 4, 5]])
display(df3)
                   
df3.index = ['r0', 'r1']
df3.columns = ['c0', 'c1', 'c2']

display(df3)

0  1  2
0  0  1  2
1  3  4  5

c0  c1  c2
r0   0   1   2
r1   3   4   5

In [27]:
print(type(df3.to_numpy()))
print(df3.to_numpy())

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]


In [29]:
b1 = np.array([ [ [0], [1], [2] ], [ [3], [4], [5] ] ])
print(type(b1))
print(b1.shape)

<class 'numpy.ndarray'>
(2, 3, 1)
